base:
  - src/Dockerfile
  - src/**
base-cargo:
  - src/base/cargo/**
  - src/base/Dockerfile
base-go:
  - src/base/go/**
  - src/base/Dockerfile
base-pyenv:
  - src/base/pyenv/**
  - src/base/Dockerfile
base-python:
  - src/base/python/**
  - src/base/Dockerfile
