name: Docker
on:
  workflow_call:
    inputs:
      src-files:
        required: true
        type: string
      image-name: string
        required: true
        type: string
jobs:
  check:
    name: Check file changes
    runs-on: ubuntu-latest
    outputs:
      filters: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: ''
          filters: |
            src: '.devcontainer/**'
  build:
    name: 'Build new image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/devcontainer
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
