version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/src'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/src/brew'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/src/brew/devtools'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
