version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/variants/base'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/variants/homebrew'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
