name: Build
on:
  workflow_call:
    inputs:
      dir:
        description: Target source directory
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        description: DockerHub Access Token
        required: true

jobs:

  list:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: ${{ inputs.dir }}/filter.yaml

  build:
    name: build / ${{ matrix.tag }}
    needs: list
    if: ${{ needs.list.outputs.tags != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJSON(needs.list.outputs.tags) }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "CONTEXT=$(echo ${{ matrix.tag }} | sed 's,-,/,g' |
            while read -r path; do
              find src -type d -path "*${path}"
            done
          )" >> $GITHUB_ENV
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ github.repository }}
          tags: type=raw,value=${{ matrix.tag }}
          github-token: ${{ github.token }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: build
        with:
          context: ${{ env.CONTEXT }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
