name: Build
on:
  workflow_call:
    inputs:
      filters:
        required: true
        type: string
      images:
        required: true
        type: string
      context:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  filter:
    name: change filter
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: ${{ inputs.filters }}
  build:
    name: 'tag: ${{ matrix.variant }}'
    needs: filter
    if: needs.filter.outputs.variants != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJSON(needs.filter.outputs.variants) }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ inputs.images }}
          tags: type=raw,value=${{ matrix.variant }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: build
        with:
          context: ${{ inputs.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
