name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pkg:
    uses:
      ${{ env.GITHUB_REPOSITORY}}/.github/workflows/action-build.yaml@latest
    with:
      dir: src/pkg
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
