# GitHub Actions workflow configuration
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: 'Lint checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: kasperhesthaven/setup-editorconfig-checker@v1.2.0
        if: always()
      # cspell:disable-next-line
      - uses: streetsidesoftware/cspell-action@v1.0.1
      # cspell:disable-next-line
      - uses: nosborn/github-action-markdown-cli@v2.0.0
        if: always()
        with:
          files: .
          config_file: .markdownlint.yaml
      # cspell:disable-next-line
      - uses: actionsx/prettier@v2
        if: always()
        with:
          args: --check .
      # cspell:disable-next-line
      - uses: luke142367/Docker-Lint-Action@v1.0.0
        if: always()
        with:
          target: variants/base/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  changes:
    name: 'Detect changed variants'
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            base: variants/base/*
  build:
    name: 'Build variant: ${{ matrix.variant }}'
    needs: changes
    if: needs.changes.outputs.variants != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        variant: ${{ fromJSON(needs.changes.outputs.variants) }}
    env:
      IMAGE_NAME: bottle-garden/github-devcontainer
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.variant }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: variants/${{ matrix.variant }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
