name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build container: ${{ matrix.variant }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [universal]
    env:
      SRC: src/${{ matrix.variant }}
      USERNAME: nomiro
      PROJECT: devcontainers
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.USERNAME }}/${{ env.PROJECT }}
          tags: type=raw,value=${{ matrix.variant }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: build
        with:
          context: ${{ env.SRC }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
