name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  src:
    name: src
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  src-base:
    name: src
    needs: src
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/base
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  src-base-py:
    name: src
    needs: src-base
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/base/py
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  src-base-py-pipx:
    name: src
    needs: src-base-py
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/base/py/pipx
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  src-base-pyenv:
    name: src
    needs: src-base-py-pipx
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/base/pyenv
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  src-base-rust:
    name: src
    needs: src-base
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/base/rust
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
