name: Push
on:
  pull_request:
  push:
    branches:
      - main

env:
    WORKFLOWS: nomiro/devcontainers/.github/workflows

jobs:
  components:
    uses: nomiro/devcontainers/.github/workflows/src-components.yaml@main
    with:
      workflows: ${{ emv.WORKFLOWS }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
