# GitHub Actions workflow configuration
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: 'Lint checks'
    # Pin the GitHub Ubuntu Ubuntu version to match the VS Code version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: kasperhesthaven/setup-editorconfig-checker@v1.2.0
        if: always()
      # cspell:disable-next-line
      - uses: streetsidesoftware/cspell-action@v1.0.1
      # cspell:disable-next-line
      - uses: nosborn/github-action-markdown-cli@v2.0.0
        if: always()
        with:
          files: .
          config_file: .markdownlint.yaml
      # cspell:disable-next-line
      - uses: actionsx/prettier@v2
        if: always()
        with:
          args: --check .
  changes:
    name: 'Detect changes'
    needs: lint
    # Pin the GitHub Ubuntu Ubuntu version to match the VS Code version
    runs-on: ubuntu-20.04
    outputs:
      variants: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            vscode/gh: src/vscode/gh/*
            vscode/gh/brew: src/vscode/gh/brew/*
            vscode/gh/brew/devtools: src/vscode/gh/brew/devtools/*
  build:
    name: 'Build variant: ${{ matrix.variant }}'
    needs: changes
    if: needs.changes.outputs.variants != '[]'
    # Pin the GitHub Ubuntu Ubuntu version to match the VS Code version
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        variant: ${{ fromJSON(needs.changes.outputs.variants) }}
    env:
      DIR: src/${{ matrix.variant }}
      ORG: bottle-garden
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ${{ env.DIR }}/Dockerfile
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ env.ORG }}/${{ matrix.variant }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ env.DIR }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
  status:
    name: 'Status'
    needs:
      - lint
      - changes
      - build
    if: always() 
    # if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: Jimdo/should-i-notify-action@main
        id: notify
        with:
          with:
            branch: main
            needs_context: ${{ toJson(needs) }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
      status:
    steps:
      if: steps.notify.outputs.should_send_message == 'yes'
      - uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.ZAPIER_WEBHOOK_URL }}
          json: '{"status": "success"}'
    steps:
      if: steps.notify.outputs.should_send_message == 'no'
      - uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.ZAPIER_WEBHOOK_URL }}
          json: '{"status": "fail"}'
