name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  base:
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/base
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  dev:
    needs: base
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/dev
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  packages:
    needs: dev
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/packages
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
