# GitHub Actions workflow configuration
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-checks:
    name: Lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: kasperhesthaven/setup-editorconfig-checker@v1.2.0
        if: always()
      # cspell:disable-next-line
      - uses: streetsidesoftware/cspell-action@v1.0.1
      # cspell:disable-next-line
      - uses: nosborn/github-action-markdown-cli@v2.0.0
        if: always()
        with:
          files: .
          config_file: .markdownlint.yaml
      # cspell:disable-next-line
      - uses: actionsx/prettier@v2
        if: always()
        with:
          args: --check .
      # cspell:disable-next-line
      - uses: luke142367/Docker-Lint-Action@v1.0.0
        if: always()
        with:
          target: src/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-push:
    name: 'Build and push'
    needs: lint-checks
    runs-on: ubuntu-latest
    env:
      VARIANT: bottle-garden/devcontainer/base
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ env.VARIANT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: src
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
