name: Push
on:
  pull_request:
  push:
    branches:
      - main

env:
  WORKFLOWS: ${{ env.GITHUB_REPOSITORY}}/.github/workflows

jobs:
  pkg:
    uses: ${{ env.WORKFLOWS }}/action-build.yaml@latest
    with:
      dir: src/pkg
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
