name: Push
on:
  pull_request:
  push:
    branches:
      - main

env:
    WORKFLOWS: ${{ env.GITHUB_REPOSITORY}}/.github/workflows

jobs:
  pkg:
    - uses: ./.github/workflows/tag-pkg.yaml@${{ github.head_ref }}
      with:
        workflows: ${{ env.WORKFLOWS}}
      secrets:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
