name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  base:
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/base
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  sdk:
    needs: base
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/sdk
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  packages:
    needs: sdk
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/packages
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  python3:
    needs: packages
    uses: nomiro/devcontainers/.github/workflows/action-build.yaml@main
    with:
      dir: src/packages/python3
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
