name: Push
on:
  pull_request:
  push:
    branches:
      - main

env:
    WORKFLOWS: nomiro/devcontainers/.github/workflows

jobs:
  components:
    uses: ./.github/workflows/src-components.yaml@${{ github.head_ref }}
    with:
      workflows: ${{ env.WORKFLOWS }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
