name: Components
on:
  workflow_call:
    inputs:
      workflows:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true

env:
    DIR: components
    ACTION: ${{ inputs.filters }}/build-matrix.yaml@main

jobs:
  env:
    SRC: .github/src/${{ env.DIR }}
  base:
    env:
      CONTEXT: ${{ env.SRC }}/${{ env.GITHUB_JOB }}
    - uses: ${{ env.ACTION }}
      secrets:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        filters: ${{ env.CONTEXT }}/filters.yaml
        images: ${{ env.GITHUB_REPOSITORY }}/${{ env.DIR }}
        context: src/${{ env.CONTEXT }}
        tag: ${{ env.GITHUB_JOB }}
  base-cargo:
    needs: base
    env:
      CONTEXT: ${{ env.SRC }}/${{ env.GITHUB_JOB }}
    - uses: ${{ env.ACTION }}
      secrets:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        filters: ${{ env.CONTEXT }}/filters.yaml
        images: ${{ env.GITHUB_REPOSITORY }}/${{ env.DIR }}
        context: src/${{ env.CONTEXT }}
        tag: ${{ env.GITHUB_JOB }}
  base-go:
    needs: base
    - run: |
        echo "SUBDIR=$(echo ${{ env.GITHUB_JOB }} | sed 's,.*-,,')" \
        >> $GITHUB_ENV
    - uses: ${{ env.ACTION }}
      secrets:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        filters: ${{ env.SRC }}/${{ env.SUBDDIR }}filters.yaml
        images: ${{ env.GITHUB_REPOSITORY }}/${{ env.DIR }}
        context: ${{ env.SRC }}
        tag: ${{ env.GITHUB_JOB }}
  base-pyenv:
    needs: base
    - uses: ${{ env.ACTION }}
      secrets:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        filters: ${{ env.SRC }}/${{ env.SUBDDIR }}filters.yaml
        images: ${{ env.GITHUB_REPOSITORY }}/${{ env.DIR }}
        context: ${{ env.SRC }}
        tag: ${{ env.GITHUB_JOB }}
  base-python:
    needs: base
    - uses: ${{ env.ACTION }}
      secrets:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        filters: ${{ env.SRC }}/${{ env.SUBDDIR }}filters.yaml
        images: ${{ env.GITHUB_REPOSITORY }}/${{ env.DIR }}
        context: ${{ env.SRC }}
        tag: ${{ env.GITHUB_JOB }}
